services:
  # Run with: 
  #   docker compose up -d
  # Access at:
  #   http://localhost:8300/?folder=/home/workspace
  gitpod-openvscode-server:
    image: gitpod/openvscode-server:1.93.1
    ports:
      - 8300:3000