services:
  mytest:
    image: busybox:1.36.1
    working_dir: /www
    volumes:
      - ./index.html:/www/index.html:ro
    ports:
      - 8300:3000
    command:
      - /bin/sh
      - -c
      - |
        echo "http://localhost:8300"
        busybox httpd -fv -p 3000 -h /www
        