# This Docker Compose file defines a Node.js web server.
#
# To run the service:
#   docker-compose run --rm box1
# 
services:
  box1:
    image: node:22.9
    working_dir: /app
    command:
      - /bin/sh
      - -c
      - |
        #
        # https://nodejs.org/api/sqlite.html
        #
        node --experimental-sqlite --no-warnings=ExperimentalWarning app.js
    volumes:
      - ./app.js:/app/app.js:ro